header:
  license:
    spdx-id: Apache-2.0
    content: |
      SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and sapcc contributors
      SPDX-License-Identifier: Apache-2.0

  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - '**'

  paths-ignore:
    - '.github/**'
    - 'REUSE.toml'
    - 'LICENSES/*.txt'
    - 'hack/**'
    - 'hack/boilerplate.go.txt'
    - 'docs/**'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'PROJECT'
    - '**/*.gitignore'
    - '**/*.helmignore'
    - '**/*.tpl'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.lock'
    - '**/*.json'
    - '**/.gitkeep'
    - '**/*.txt'
    - '*Dockerfile*'
    - 'Makefile'
    - 'VERSION'
    
  comment: on-failure
  
  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80

  language:
    JSX: 
      extensions:
        - ".jsx"
      comment_style_id: SlashAsterisk