# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0

# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and sapcc contributors
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view digicertissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: digicertissuer-viewer-role
rules:
- apiGroups:
  - certmanager.cloud.sap
  resources:
  - digicertissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certmanager.cloud.sap
  resources:
  - digicertissuers/status
  verbs:
  - get
