# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and sapcc contributors
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to edit digicertissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: digicertissuer-editor-role
rules:
- apiGroups:
  - certmanager.cloud.sap
  resources:
  - digicertissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certmanager.cloud.sap
  resources:
  - digicertissuers/status
  verbs:
  - get
