# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0

# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and sapcc contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: certificate-example
spec:
  # The secret name to store the signed certificate
  secretName: somednsname-tld
  # Common Name
  commonName: someDnsName.tld
  # DNS SAN
  dnsNames:
    - someDnsName.tld
  # Renew 720h (30d) before the certificate expiration.
  renewBefore: 720h
  # The reference to the step issuer
  issuerRef:
    group: certmanager.cloud.sap
    kind: Issuer
    name: digicert-issuer
