# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and sapcc contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: digicertissuer-secret

data:
  DIGICERT_API_TOKEN: YourBase64EncodedDigicertApiTokenGoesHere
