# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
# SPDX-License-Identifier: Apache-2.0

# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and sapcc contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: digicert-issuer
  labels:
    app.kubernetes.io/name: digicert-issuer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: digicert-issuer
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: digicert-issuer
    spec:
      containers:
      - command:
        - /digicert-issuer
        args:
        - --enable-leader-election
        image: digicert-issuer:latest
        name: digicert-issuer
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 60Mi
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
